import Head from "next/head";
import { useSession } from "next-auth/react";
import { Avatar, Box, CircleBadge, Header } from "@primer/react";
import {Heading, Button} from '@primer/react'


export default function Home() {
const { data } = useSession();

return (
<>

  <Head>
    <title>Automated Theorem Prover</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />
  </Head>



  <main>
    <div style={{   
  
  height: "100vh",  
 
 }}>


      <div style={{ 
            position: "relative",
            fontSize: "2.25rem",
            fontWeight:"bold",
            display: "block", 
            placeItems: "center" ,
            
              height: "60%",
              width: "100%",
         
            
        }}>

        Automated Theorem Prover

    


      <Box sx={{paddingY: 4, textAlign: 'left', fontSize:'20px',  fontWeight:"normal",}}>
        The aim is to understand in detail how humans find proofs, and then to use that understanding to program
        computers to find proofs in the same way.
      </Box>

      </div>


      <Box sx={{
            margin: "0 auto",
            width: "800px",
            display: "flex",
            p: 4,
            backgroundColor: "canvas.inset",
            borderRadius: 6,
            color: "fg.muted",
            justifyContent: "space-between"
          }}>


        {data ? (
        <>
          <CircleBadge size={40}>
            <Avatar size={20} src={`${data.user?.image}`} />

          </CircleBadge>
          <div style={{ justifySelf:"right", padding:"2px"}}> {data.user?.name}</div>


        </>
        ) : (
        "Sign in to get started!"
        )}
      </Box>
    </div>
  </main>
</>
);
}